version: 2

builds:
  - id: gh-agent-viz
    main: ./gh-agent-viz.go
    binary: gh-agent-viz
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/maxbeizer/gh-agent-viz/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - binary
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
